resourcedir = '../resources/'
publishDir = '../docs'
title = 'My Hugo Hinode Site'
copyright = "Copyright © 2024 Serguei Vine."

baseURL = 'https://vinser.github.io/hugo-hinode/'
# canonifyAssetsURLs = true

# languageCode = "en-us"
# defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true

[[module.imports]]
    path = 'github.com/gethinode/hinode'
