[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [en.params.head]
        tagline = "Cloud Library"
    [en.params.footer]
        license = "Code licensed <a href='https://github.com/vinser/flibgolite/blob/master/LICENSE' class='link-bg-footer fw-medium' target='_blank' rel='noopener noreferrer'>MIT</a>, docs <a href='https://creativecommons.org/licenses/by-nc/4.0/' class='link-bg-footer fw-medium' target='_blank' rel='noopener noreferrer'>CC BY-NC 4.0</a>"
[ru]
    languageName = "Русский"
    contentDir = "content/ru"
    weight = 2
    [ru.params.head]
        tagline = "облачная библиотека"
    [ru.params.footer]
        license = "Code licensed <a href='https://github.com/vinser/flibgolite/blob/master/LICENSE' class='link-bg-footer fw-medium' target='_blank' rel='noopener noreferrer'>MIT</a>, docs <a href='https://creativecommons.org/licenses/by-nc/4.0/' class='link-bg-footer fw-medium' target='_blank' rel='noopener noreferrer'>CC BY-NC 4.0</a>"

[uk]
    languageName ="Українська"
    contentDir = "content/uk"
    weight = 3
    [uk.params.head]
        tagline = "хмарна бібліотека"
    [uk.params.footer]
        license = "Code licensed <a href='https://github.com/vinser/flibgolite/blob/master/LICENSE' class='link-bg-footer fw-medium' target='_blank' rel='noopener noreferrer'>MIT</a>, docs <a href='https://creativecommons.org/licenses/by-nc/4.0/' class='link-bg-footer fw-medium' target='_blank' rel='noopener noreferrer'>CC BY-NC 4.0</a>"
