[en]
languageName = "English"
contentDir = "content/en"
weight = 10

# [en.params.head]
# tagline = "A Hugo Theme"
# [en.params.social]
# title = "Follow me"
# caption = "I work on everything coding and tweet developer memes"
# [en.params.footer]
# # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
# # toml-docs-end lang-param
# [en.params.sections.blog]
# reference = "More Posts"
# [en.params.sections.projects]
# reference = "More Projects"

[ru]
languageName = "Русский"
contentDir = "content/ru"
weight = 20
# [en.params.head]
# tagline = "A Hugo Theme"
# [en.params.social]
# title = "Follow me"
# caption = "I work on everything coding and tweet developer memes"
# [en.params.footer]
# # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
# # toml-docs-end lang-param
# [en.params.sections.blog]
# reference = "More Posts"
# [en.params.sections.projects]
# reference = "More Projects"


