[main]
    [main.externalLinks]
        cue = true
        tab = true

# [home]
#     sections = ["apps","news"]
#     fullCover = false
#     centerHeadline = false
#     style = ""
#     [home.feature]
#         orientation = "horizontal"
#         color = "primary"
#         width = 4
#         align = "center"

[navigation]
    logo = "img/SV-1-1.svg"

[sections]
    [sections.apps]
        # title = "My crafted apps"
        # layout = "nav"
        sort = "weight"
        header = "none"
        ratio = "4x3"
    [sections.news]
        title = "News about me and my crafts"

[sharing]
    enabled = false

[minify]
  [minify.tdewolff.html]
    keepWhitespace = true

[links]
    flibgolite_project = "https://github.com/vinser/flibgolite"
    pixyne_project = "https://github.com/vinser/pixyne"
    burnfix_project = "https://github.com/vinser/burnfix"
    flibgolite_site = "https://vinser.github.io/flibgolite"
    pixyne_site = "https://vinser.github.io/pixyne"
    burnfix_site = "https://vinser.github.io/burnfix"
    # burnfix_site = "burnfix"
