[main]
    separator = "-"
    description = "FLibGoLite is a lightweight OPDS server for home library and more"
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = true
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = true
        tab = true
    [main.build]
        transpiler = "libsass"

[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false

[docs]
    latestTag = "v2.0.0"
    basePath = "assets/files"
    github = "https://github.com/vinser/flibgolite"
    release = "https://github.com/vinser/flibgolite/releases/tag/"
    checkVersion = false
    showDocTOCTitle = true
    
[home]
    sections = ["dummy"]
    fullCover = true
    centerHeadline = true
    # style = "gradient-featured"
    [home.feature]
        orientation = "stacked"
        color = "secondary"
        width = 8
        align = "start"

[navigation]
    logo = "/img/logo-1.svg"
    color = "primary"
    offset = "3.5em"
    fixed = true
    anchor = true
    search = true
    breadcrumb = false
    toc = true
    sidebar = true
    size = "lg"
    # style = "dark"
    # overlay = false
    # overlayMode = "light"

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    # url = "https://api.whatsapp.com/send?text={url}%20data-action=\"share/whatsapp/share\""
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "telegram"
    url = "https://t.me/share/url?text={title}&url={url}"
    # url = "https://telegram.me/share/url?url={url}&text={title}"
    icon = "fab telegram"
    weight = 50
[[sharing.providers]]
    name = "link"
    url = "{url}"
    icon = "fas link"
    weight = 60
    clipboard = true

# [sections]
#     [sections.docs]
#         title = "Components"
#         layout = "card"
#         sort = "title"
#         reverse = false
#         nested = false
#         background = ""
#         color = "body-tertiary"
#         style = "border-0 shadow card-feature card-shrink card-body-margin"
#         cols = 3
#         padding = "3"
#         header = "none"
#         footer = "none"
#         orientation = "stacked"
#         homepage = 3

[favicon]
    logo = "icons/favicon.png"
    sizes = [16, 32, 48]

[style]
    # primary = "#D43900"
    # secondary = "#6c757d"
    # success = "#198754"
    # info = "#0dcaf0"
    # warning = "#ffc107"
    # danger = "#dc3545"
    # light = "#f8f9fa"
    # dark = "#212529"
    primary = "#30638E"
    # primary = "#253543"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "25"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    themeFontPath = "/fonts" # local path
    themeFontPreload = "/fonts/inter-v12-latin-regular.woff2"
    fontSizeBase = "1rem"

[schema]
    type = "Person"
    name = "FLibGoLite"
    locale = "en-US"
    github = "https://github.com/vinser/flibgolite"
    section = "dosc"
    [author]
        name = "Serguei Vine"
        github = "https://github.com/vinser"
#     [logo]
#         url = "img/logo512x512.png"
#         width = 512
#         height = 512
#     [image]
#         url = "img/logo1280x640.png"
#         width = 1280
#         height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[links]
    repository = "https://github.com/vinser/flibgolite/"
    repository_tag = "https://github.com/vinser/flibgolite/releases/tag/"
    repository_releases = "https://github.com/vinser/flibgolite/releases/"
    repository_issues = "https://github.com/vinser/flibgolite/issues/"
    golang_install = "https://go.dev/doc/install"
    git_install = "https://git-scm.com/book/en/v2/Getting-Started-Installing-Git"
    sqlite_home = "https://sqlite.org/"
    wiki_opds = "https://en.wikipedia.org/wiki/Open_Publication_Distribution_System"
    wiki_epub = "https://en.wikipedia.org/wiki/EPUB"
    wiki_fb2 = "https://en.wikipedia.org/wiki/FictionBook"
    ietf_language_tags = "https://en.wikipedia.org/wiki/IETF_language_tag"
    project_gutenberg = "https://www.gutenberg.org/"